### ISSUE TITLE
Initialization Error and ShellJS File Writing Issue

### ISSUE THREAD

**Issue by ghost** [ariym/whisper-node#28]
On Debian GNU/Linux 10 (buster), I encountered a ploblem while deploying a NodeJS project on [Render](https://render.com/). It appears that the module is not initializing correctly on it.

```shell
[whisper-node] Problem. whisper.cpp not initialized. Current shelljs directory:  /opt/render/project/src/node_modules/whisper-node/dist
[whisper-node] Attempting to run 'make' command in /whisper directory...
error caught in try catch block
node:fs:2352
    return binding.writeFileUtf8(
                   ^

Error [ShellJSInternalError]: ENOENT: no such file or directory, open '/tmp/shelljs_ec87588fed5a22cbb957'
    at Object.writeFileSync (node:fs:2352:20)
    at writeFileLockedDown (/opt/render/project/src/node_modules/shelljs/src/exec.js:61:8)
    at execSync (/opt/render/project/src/node_modules/shelljs/src/exec.js:66:3)
    at Object._exec (/opt/render/project/src/node_modules/shelljs/src/exec.js:223:12)
    at Object.exec (/opt/render/project/src/node_modules/shelljs/src/common.js:335:23)
    at Object.<anonymous> (/opt/render/project/src/node_modules/whisper-node/dist/shell.js:53:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/shelljs_ec87588fed5a22cbb957'
}
```

**Comment by ariym** [comment]
See if you're able to run whisper.cpp in debian by cloning the [original repo](https://github.com/ggerganov/whisper.cpp). This may not be a whisper-node issue
